services:
  backend:
    build:
      args:
        - DEV=false
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings_prod
    command: ["daphne", "-p", "8000", "-b", "0.0.0.0", "app.asgi:application"]
  
  cron:
    image: alpine
    container_name: tr_cron
    volumes:
      - django-media:/app/media
    depends_on:
      - backend
    entrypoint: /bin/sh
    command:
      - -c
      - |
          crontab - <<'EOF'
          * * * * * find /app/media/qrcode -name 'qr*' -type f -mmin +10 -delete
          EOF

          exec crond -f